---

- name: "Install Ubuntu dependencies with apt"
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - build-essential 
    - cmake 
    - curl 
    - gawk 
    - git 
    - gnuplot 
    - graphviz 
    - openjdk-8-jre 
    - libarchive-dev 
    - liblzma-dev 
    - libbz2-dev 
    - libncurses5-dev 
    - libncursesw5-dev 
    - zlib1g-dev 
    - pkg-config 
    - python-dev 
    - python-pip 
    - python3-dev 
    - python3-pip 
    - python3-setuptools 
    - r-base-core 
    - rsync 
    - unzip 
    - wget
